### ISSUE TITLE
Why was css extension kept as URL? What if we wish to load CSS into the styles using loaders?

### ISSUE THREAD

**Issue by vaidsu** [airbnb/nimbus#12]
I am trying to use the config and extend by adding more loaders like this :

```js
const config = require('./node_modules/@irbnb/nimbus/configs/webpack.js');

config.module.rules.push({
  test: /\.md$/i,
  use: 'raw-loader',
});

config.module.rules.push({
  test: /\.css$/i,
  use: ['style-loader', 'css-loader'],
});

module.exports = config;
```

While the raw loader works, and I don't get any errors for css loader, I always get my css load as an URL like below: 

```jsx
import css from './assets/news.css';

console.log(css) // data:text/css;base64,dmF...
```

1. I tried to fork and install that, but that was cumbersome. 
2. I tried to copy paste the whole config to eject completely, but that was difficult to avoid a lot of goodness and additional install. 

How do I go about this please?

**Comment by milesj** [comment]
@vaidsu Use `unshift` instead of `push`. Otherwise the CSS is loaded here instead: https://github.com/airbnb/nimbus/blob/master/packages/config-webpack/index.js#L108

**Comment by vaidsu** [comment]
Aaah interesting, didn't think of thatt. `unshift` is a tricky name to say first in list. Thanks @milesj 👍
