### ISSUE TITLE
enzyme-to-json missing from peer

### ISSUE THREAD

**Issue by mmahalwy** [airbnb/nimbus#17]
Used here: https://github.com/airbnb/nimbus/blob/f75536ad05b48deddea91975466f9d76ddf467b8/packages/config-jest/enzyme.js#L2

**Comment by milesj** [comment]
@mmahalwy It's not a dependency (or a peer) on purpose since the Enzyme functionality is opt-in.

It's mentioned in our documentation that these deps need to be installed manually.

**Comment by milesj** [comment]
Can maybe solve this with `optionalPeerDependencies`.

**Comment by milesj** [comment]
Added as optional peers in next version.
